#!/usr/bin/env python3
"""
NexDev Architecture Decision Records (ADR) Manager (Phase 3 Feature)

Auto-generates and manages ADRs for major design decisions.
Creates searchable archive of architectural choices with context.
Part of NexDev v3.0 World-Class Build Team Upgrade
"""

import json
from pathlib import Path
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, asdict
from datetime import datetime


@dataclass
class ADREntry:
    """Represents an Architecture Decision Record."""
    id: str
    title: str
    status: str  # "proposed", "accepted", "rejected", "superseded"
    context: str  # What is the issue we're addressing?
    decision: str  # What is the change we're proposing
    consequences: str  # What becomes easier/harder
    alternatives_considered: List[str]
    related_adrs: List[str]
    author: str
    date_created: str
    date_decided: Optional[str] = None
    decided_by: Optional[str] = None
    
    def to_dict(self):
        return {
            "id": self.id,
            "title": self.title,
            "status": self.status,
            "context": self.context,
            "decision": self.decision,
            "consequences": self.consequences,
            "alternatives_considered": self.alternatives_considered,
            "related_adrs": self.related_adrs,
            "author": self.author,
            "date_created": self.date_created,
            "date_decided": self.date_decided,
            "decided_by": self.decided_by
        }


ADRs_DIR = Path.home() / ".openclaw/workspace/nexdev/ADRs"


def init_adrs_directory():
    """Initialize ADRs directory structure."""
    ADRs_DIR.mkdir(parents=True, exist_ok=True)
    
    # Create index file if it doesn't exist
    index_path = ADRs_DIR / "index.json"
    if not index_path.exists():
        with open(index_path, 'w') as f:
            json.dump({"adrs": [], "version": "1.0"}, f, indent=2)


def save_adr(adr: ADREntry):
    """Save ADR to file system."""
    init_adrs_directory()
    
    # Save individual file
    filename = f"{adr.id}.md"
    filepath = ADRs_DIR / filename
    
    content = generate_adr_markdown(adr)
    filepath.write_text(content)
    
    # Update index
    update_adr_index(adr)


def generate_adr_markdown(adr: ADREntry) -> str:
    """Generate markdown format for ADR."""
    
    md = f"""# {adr.id}: {adr.title}

| Field | Value |
|-------|-------|
| **Status** | {adr.status} |
| **Created** | {adr.date_created[:10]} |
| **Author** | {adr.author} |

---

## Context

{adr.context}

---

## Decision

{adr.decision}

---

## Consequences

### Benefits
- Improved maintainability
- Reduced technical debt

### Trade-offs
- Added complexity upfront
- Learning curve for team

---

## Alternatives Considered

{chr(10).join([f"- {alt}" for alt in adr.alternatives_considered])}

---

## Related ADRs

{chr(10).join([f"- [{rel_id}]({rel_id}.md)" for rel_id in adr.related_adrs])}

---

*Generated by NexDev v3.0 on {datetime.now().isoformat()}*
"""
    return md


def update_adr_index(adr: ADREntry):
    """Update ADR index with new entry."""
    index_path = ADRs_DIR / "index.json"
    
    with open(index_path, 'r') as f:
        index = json.load(f)
    
    # Check if exists
    existing_idx = next((i for i, a in enumerate(index["adrs"]) if a["id"] == adr.id), None)
    
    entry_summary = {
        "id": adr.id,
        "title": adr.title,
        "status": adr.status,
        "created": adr.date_created,
        "author": adr.author
    }
    
    if existing_idx is not None:
        index["adrs"][existing_idx] = entry_summary
    else:
        index["adrs"].append(entry_summary)
    
    # Sort by date created
    index["adrs"].sort(key=lambda x: x["created"], reverse=True)
    
    with open(index_path, 'w') as f:
        json.dump(index, f, indent=2)


def get_all_adrs() -> List[Dict[str, Any]]:
    """Get all ADRs from index."""
    init_adrs_directory()
    index_path = ADRs_DIR / "index.json"
    
    try:
        with open(index_path, 'r') as f:
            index = json.load(f)
        return index.get("adrs", [])
    except Exception:
        return []


def get_adr(adr_id: str) -> Optional[Dict[str, Any]]:
    """Retrieve ADR by ID."""
    init_adrs_directory()
    filepath = ADRs_DIR / f"{adr_id}.md"
    
    if not filepath.exists():
        return None
    
    with open(filepath, 'r') as f:
        content = f.read()
    
    # Parse metadata from markdown
    lines = content.split('\n')
    title = ""
    status = "unknown"
    
    for line in lines:
        if line.startswith('#'):
            title = line.lstrip('# ').strip()
            break
    
    for line in lines:
        if '**Status**' in line:
            status = line.split('|')[2].strip()
            break
    
    return {
        "id": adr_id,
        "title": title,
        "status": status,
        "content": content
    }


def search_adrs(query: str) -> List[Dict[str, Any]]:
    """Search ADRs by keyword."""
    results = []
    query_lower = query.lower()
    
    for adr_summary in get_all_adrs():
        if query_lower in adr_summary["title"].lower():
            adr = get_adr(adr_summary["id"])
            if adr:
                results.append(adr)
    
    return results


def suggest_adrs_for_decision(decision_description: str, tech_stack: List[str]) -> List[Dict[str, Any]]:
    """Suggest relevant existing ADRs for a new decision."""
    # Simple heuristic: match keywords from decision description
    words = decision_description.lower().split()
    
    suggestions = []
    for word in ["database", "cache", "auth", "api", "security", "performance"]:
        if any(word in w for w in words):
            # Search for related ADRs
            related = search_adrs(word)
            suggestions.extend(related)
    
    # Deduplicate
    seen_ids = set()
    unique_suggestions = []
    for sug in suggestions:
        if sug["id"] not in seen_ids:
            seen_ids.add(sug["id"])
            unique_suggestions.append(sug)
    
    return unique_suggestions


if __name__ == "__main__":
    # Demo mode
    print("=" * 60)
    print("📜 NEXDEV ADR MANAGER - DEMO")
    print("=" * 60)
    
    init_adrs_directory()
    
    # Sample ADR
    sample_adr = ADREntry(
        id="ADR-001",
        title="Use PostgreSQL over MongoDB for primary database",
        status="accepted",
        context="We need a database for our application. Options are PostgreSQL (relational) or MongoDB (document store). Our data has clear relationships and ACID compliance is important.",
        decision="Choose PostgreSQL because:\n\n1. Strong consistency requirements\n2. Complex queries with joins needed\n3. Better transaction support\n4. Team familiarity with SQL",
        consequences="PostgreSQL will be our primary database. Migrations required for schema changes. We'll use Django ORM for access.",
        alternatives_considered=[
            "MongoDB - rejected due to lack of ACID transactions",
            "MySQL - similar but PostgreSQL has better JSON support",
            "SQLite - not suitable for production scale"
        ],
        related_adrs=["ADR-002"],
        author="architecture-team",
        date_created=datetime.now().isoformat(),
        date_decided=datetime.now().isoformat(),
        decided_by="tech-leads"
    )
    
    save_adr(sample_adr)
    
    print(f"\n✅ Saved ADR: {sample_adr.id}")
    print(f"   Title: {sample_adr.title}")
    print(f"   Status: {sample_adr.status}")
    
    # List all ADRs
    all_adrs = get_all_adrs()
    print(f"\n📊 Total ADRs: {len(all_adrs)}")
    
    if all_adrs:
        print("\nRecent ADRs:")
        for adr in all_adrs[:5]:
            print(f"  • {adr['id']}: {adr['title']} [{adr['status']}]")
    
    # Test suggestion
    print("\n" + "=" * 60)
    print("SUGGESTION TEST")
    print("=" * 60)
    
    new_decision = "Need to choose authentication mechanism for user login"
    tech_stack = ["Python", "PostgreSQL", "Redis"]
    
    suggestions = suggest_adrs_for_decision(new_decision, tech_stack)
    print(f"\nDecision: '{new_decision}'")
    print(f"Tech stack: {', '.join(tech_stack)}")
    print(f"Suggested ADRs: {len(suggestions)}")
    
    for sug in suggestions:
        print(f"  • {sug['id']}: {sug['title']}")
    
    print("\n" + "=" * 60)
    print("Demo complete!")
