#!/usr/bin/env python3
"""
NexDev CI/CD Pipeline Generator (Tier 1 Feature)

Auto-generates GitHub Actions, GitLab CI, and Jenkins pipelines.
Integrates with test framework detection for full automation.
Part of NexDev v3.0 World-Class Build Team Upgrade
"""

import re
from pathlib import Path
from typing import Dict, Any, List, Optional
from datetime import datetime

# ──────────────────────────────────────────────────────────────────────────────
# Language & Framework Detection
# ──────────────────────────────────────────────────────────────────────────────

LANGUAGE_TO_CONFIG = {
    "python": {
        "github": "github-actions-python",
        "gitlab": "gitlab-python",
        "package_manager": "pip",
        "test_command": "pytest"
    },
    "javascript": {
        "github": "github-actions-nodejs",
        "gitlab": "gitlab-nodejs",
        "package_manager": "npm",
        "test_command": "npm test"
    },
    "typescript": {
        "github": "github-actions-nodejs-ts",
        "gitlab": "gitlab-nodejs-ts",
        "package_manager": "npm",
        "test_command": "npm test"
    },
    "java": {
        "github": "github-actions-java",
        "gitlab": "gitlab-java-maven",
        "package_manager": "maven",
        "test_command": "mvn test"
    },
    "go": {
        "github": "github-actions-go",
        "gitlab": "gitlab-go",
        "package_manager": "go",
        "test_command": "go test ./..."
    },
    "ruby": {
        "github": "github-actions-ruby",
        "gitlab": "gitlab-ruby",
        "package_manager": "bundle",
        "test_command": "bundle exec rspec"
    }
}


def detect_project_type(project_dir: str) -> Dict[str, Any]:
    """
    Detect project type from directory structure.
    
    Args:
        project_dir: Root directory of the project
        
    Returns:
        Dictionary with detected language, frameworks, and config files found
    """
    project_path = Path(project_dir)
    
    # Check for language indicators
    indicators = {
        "python": [
            "requirements.txt", "setup.py", "pyproject.toml", 
            "Pipfile", ".pylintrc", "manage.py"
        ],
        "javascript": [
            "package.json", "yarn.lock", "node_modules",
            ".eslintrc", ".babelrc"
        ],
        "typescript": [
            "tsconfig.json", "package.json"
        ],
        "java": [
            "pom.xml", "build.gradle", "settings.gradle", "mvnw"
        ],
        "go": [
            "go.mod", "go.sum"
        ],
        "ruby": [
            "Gemfile", "Rakefile", ".rspec"
        ]
    }
    
    detected_languages = []
    config_files = {}
    
    for lang, files in indicators.items():
        matches = []
        for f in files:
            if (project_path / f).exists():
                matches.append(f)
        
        if matches:
            detected_languages.append(lang)
            config_files[lang] = matches
    
    # Primary language is first match
    primary_language = detected_languages[0] if detected_languages else "unknown"
    
    return {
        "primary_language": primary_language,
        "all_languages": detected_languages,
        "config_files": config_files,
        "has_tests": _check_for_tests_directory(project_path),
        "framework": _detect_test_framework(project_path)
    }


def _check_for_tests_directory(project_path: Path) -> bool:
    """Check if project has a tests directory."""
    possible_names = ["tests", "test", "spec", "__tests__"]
    return any((project_path / name).is_dir() for name in possible_names)


def _detect_test_framework(project_path: Path) -> str:
    """Detect the test framework being used."""
    # Python
    if (project_path / "pytest.ini").exists():
        return "pytest"
    if (project_path / "tox.ini").exists():
        return "tox"
    
    # JavaScript/TypeScript
    if (project_path / "jest.config.js").exists():
        return "jest"
    if (project_path / ".mocharc.json").exists():
        return "mocha"
    
    # Java
    if (project_path / "pom.xml").exists():
        pom_content = (project_path / "pom.xml").read_text()
        if "junit" in pom_content:
            return "junit"
    
    # Ruby
    if (project_path / ".rspec").exists():
        return "rspec"
    
    return "unknown"


# ──────────────────────────────────────────────────────────────────────────────
# GitHub Actions Generators
# ──────────────────────────────────────────────────────────────────────────────

def generate_github_actions_python(project_info: Dict[str, Any]) -> str:
    """Generate GitHub Actions workflow for Python projects."""
    return f'''# Auto-generated by NexDev v3.0
# Generated at: {datetime.now().isoformat()}

name: CI Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    name: Test ({{{{ matrix.python-version }}}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python {{{{ matrix.python-version }}}}
        uses: actions/setup-python@v5
        with:
          python-version: {{{{ matrix.python-version }}}}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{{{ runner.os }}}}-pip-${{{{ matrix.python-version }}}}-${{{{ hashFiles('**/requirements*.txt') }}}}
          restore-keys: |
            ${{{{ runner.os }}}}-pip-${{{{ matrix.python-version }}}}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          
      - name: Run linter
        run: |
          pip install flake8 black mypy
          black --check . || true
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          mypy . --ignore-missing-imports || true
          
      - name: Run security scan
        run: |
          pip install safety bandit
          safety check -r requirements.txt || echo "Security warnings above"
          bandit -r . || echo "Bandit warnings above"

      - name: Run tests with coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=. --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: success()
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{{{ secrets.PYPI_API_TOKEN }}}}
        run: twine upload dist/*

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy (placeholder)
        run: |
          echo "Deploying to production..."
          # TODO: Add your deployment steps here
          # Example: ssh deploy-user@host "cd /app && git pull && docker-compose up -d"
'''


def generate_github_actions_nodejs(project_info: Dict[str, Any]) -> str:
    """Generate GitHub Actions workflow for Node.js projects."""
    return f'''# Auto-generated by NexDev v3.0
# Generated at: {datetime.now().isoformat()}

name: CI Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

env:
  NODE_VERSION: '20.x'

jobs:
  lint-and-test:
    name: Lint & Test (Node.js {{{{ matrix.node-version }}}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js {{{{ matrix.node-version }}}}
        uses: actions/setup-node@v4
        with:
          node-version: {{{{ matrix.node-version }}}}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint --if-present

      - name: Run type checker
        run: npm run type-check --if-present

      - name: Run security audit
        run: |
          npm audit --audit-level=moderate || echo "Security vulnerabilities found above"

      - name: Run tests with coverage
        run: npm run test:cov --if-present || npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: success()
        with:
          flags: unittests
          name: codecov-umbrella

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '{project_info.get("node_version", "20")}'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - name: Deploy (placeholder)
        run: |
          echo "Deploying to production..."
          # TODO: Add your deployment steps here
          # Examples:
          # - AWS S3: aws s3 sync dist/ s3://your-bucket
          # - Docker: docker build -t your-app && docker push your-registry/your-app
          # - Vercel: vercel --prod
'''


# ──────────────────────────────────────────────────────────────────────────────
# GitLab CI Generators
# ──────────────────────────────────────────────────────────────────────────────

def generate_gitlab_ci_python(project_info: Dict[str, Any]) -> str:
    """Generate GitLab CI pipeline for Python projects."""
    return f'''# Auto-generated by NexDev v3.0
# Generated at: {datetime.now().isoformat()}

image: python:3.11

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

stages:
  - lint
  - test
  - build
  - deploy

# Lint stage
flake8:
  stage: lint
  script:
    - pip install flake8 black mypy
    - black --check . || true
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - mypy . --ignore-missing-imports || true

# Test stage
pytest:
  stage: test
  script:
    - pip install -r requirements.txt || true
    - pip install pytest pytest-cov
    - pytest --cov=. --cov-report=xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura_xml
        path: coverage.xml
  coverage: '/total.*?([0-9]{1,3}%)/'

# Build stage
build:
  stage: build
  script:
    - pip install build twine
    - python -m build
  artifacts:
    paths:
      - dist/
  only:
    - main
    - master

# Deploy stage
deploy_production:
  stage: deploy
  script:
    - echo "Deploying to production..."
    # TODO: Add your deployment commands
    # Example:
    # - ssh deploy-user@host "cd /app && git pull && systemctl restart app"
  only:
    - main
    - master
  environment:
    name: production
'''


# ──────────────────────────────────────────────────────────────────────────────
# Main Generation Functions
# ──────────────────────────────────────────────────────────────────────────────

def generate_ci_pipeline(project_dir: str, platform: str = "github") -> Dict[str, Any]:
    """
    Generate CI/CD pipeline configuration for a project.
    
    Args:
        project_dir: Root directory of the project
        platform: "github" or "gitlab"
        
    Returns:
        Dictionary with generated pipeline configuration
    """
    project_path = Path(project_dir)
    project_info = detect_project_type(project_dir)
    
    language = project_info['primary_language']
    
    result = {
        "success": False,
        "project_dir": project_dir,
        "detected_language": language,
        "platform": platform,
        "files_created": []
    }
    
    if platform.lower() == "github":
        if language == "python":
            content = generate_github_actions_python(project_info)
            workflow_file = project_path / ".github/workflows/ci.yml"
        elif language in ["javascript", "typescript"]:
            content = generate_github_actions_nodejs(project_info)
            workflow_file = project_path / ".github/workflows/ci.yml"
        else:
            result["message"] = f"No GitHub Actions template for {language}"
            return result
            
    elif platform.lower() == "gitlab":
        if language == "python":
            content = generate_gitlab_ci_python(project_info)
            workflow_file = project_path / ".gitlab-ci.yml"
        else:
            result["message"] = f"No GitLab CI template for {language}"
            return result
    else:
        result["message"] = f"Unsupported platform: {platform}"
        return result
    
    # Create directory and write file
    workflow_file.parent.mkdir(parents=True, exist_ok=True)
    workflow_file.write_text(content)
    
    result["success"] = True
    result["files_created"].append(str(workflow_file))
    result["message"] = f"Generated {platform.title()} CI pipeline for {language} project"
    
    return result


def add_complete_ci_setup(project_dir: str) -> Dict[str, Any]:
    """
    Add complete CI/CD setup including both GitHub and GitLab configs.
    
    Args:
        project_dir: Root directory of the project
        
    Returns:
        Summary of all configurations created
    """
    project_path = Path(project_dir)
    results = []
    
    # Generate for GitHub Actions
    gh_result = generate_ci_pipeline(project_dir, "github")
    results.append(gh_result)
    
    # Generate for GitLab CI
    gl_result = generate_ci_pipeline(project_dir, "gitlab")
    results.append(gl_result)
    
    return {
        "project_dir": project_dir,
        "summary": {
            "github_actions": gh_result.get("success", False),
            "gitlab_ci": gl_result.get("success", False),
            "total_files": len([r for r in results if r.get("success")])
        },
        "detailed_results": results
    }


if __name__ == "__main__":
    # Demo mode
    print("=" * 60)
    print("🔄 NEXDEV CI PIPELINE GENERATOR - DEMO")
    print("=" * 60)
    
    # Test on current workspace
    workspace_dir = str(Path.home() / ".openclaw/workspace")
    
    print(f"\nScanning project: {workspace_dir}")
    
    project_info = detect_project_type(workspace_dir)
    
    print(f"\nDetected:")
    print(f"  Language: {project_info['primary_language']}")
    print(f"  Config files: {project_info['config_files']}")
    print(f"  Has tests: {project_info['has_tests']}")
    print(f"  Test framework: {project_info['framework']}")
    
    print("\nGenerating CI pipeline...")
    
    result = generate_ci_pipeline(workspace_dir, "github")
    
    if result["success"]:
        print(f"\n✅ Success!")
        print(f"  Files created: {result['files_created']}")
        print(f"  Message: {result['message']}")
        
        # Show preview
        if result['files_created']:
            first_file = result['files_created'][0]
            print(f"\n📄 Preview of generated file ({first_file}):")
            print("-" * 60)
            
            with open(first_file) as f:
                lines = f.readlines()[:50]  # First 50 lines
            for line in lines:
                print(line.rstrip())
            
            if len(lines) >= 50:
                print("... (truncated)")
    else:
        print(f"\n❌ Error: {result.get('message', 'Unknown error')}")
    
    print("\n" + "=" * 60)
    print("Demo complete!")
